### ISSUE TITLE
skip:  unrecoverably mismatched region length

### ISSUE THREAD

**Issue by elija-feigl** [lorenzo-rovigatti/tacoxDNA#14]
Issue:
Bug in Cadnano_oxDNA.py: Cadnano to oxDNA converter.
the Cadnano file has to have the following motifs:
* square lattice
* a double-stranded segment ending with a scaffold 1 base longer than the staple
 * a skip occurring later in that helix
--> critical error  raised
the error disappears:
* without the skip
* if the scaffold overhang is longer than 1 or 0
(also see minimal example)

minimal example:
[cadnano-tacox-mismatch.json.txt](https://github.com/lorenzo-rovigatti/tacoxDNA/files/3879513/cadnano-tacox-mismatch.json.txt)
>> python cadnano_oxDNA.py cadnano-tacox-mismatch.json sq
>>
>>"CRITICAL: the lengths of begin (2) and end (3) arrays are unrecoverably mismatched"

**Comment by lorenzo-rovigatti** [comment]
The bug has been fixed by @mckwxp
