### ISSUE TITLE
vHelix to oxDNA(beta) 

### ISSUE THREAD

**Issue by asdxzsa** [lorenzo-rovigatti/tacoxDNA#15]
Hello,

Only a few days ago, I find this good site and use it. But what worked well until yesterday doesn't work today. So, I tested with the "vhelix_oxDNA.ma"
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/39143997/70195239-808c8b80-1748-11ea-8f84-9c1671059516.png">
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/39143997/70195240-808c8b80-1748-11ea-87de-2891f7d4c0f1.png">

 file but still does not work, and I have left it all day to give enough time, but it's not working. Nothing happens after I hit the "Generate" button. I ask your advice on how to solve the problem.

Thank you.

**Comment by lorenzo-rovigatti** [comment]
Hey! Thank you very much for pointing out the issue, which has been now fixed.
