### ISSUE TITLE
Incorrectly labeled flag in the README description of cadnano_oxDNA.py

### ISSUE THREAD

**Issue by jcalumba** [lorenzo-rovigatti/tacoxDNA#16]
The sequence flag is listed as -q\, but is actually -s\ as per current usage, to manually set the sequence file when using cadnano_oxDNA.py

**Comment by lorenzo-rovigatti** [comment]
Fixed in commit [35deac6](https://github.com/lorenzo-rovigatti/tacoxDNA/commit/35deac6a52950067fd90edf26895d1459127644d)
