### ISSUE TITLE
vHelix_oxDNA.py changes G in C and vice versa 

### ISSUE THREAD

**Issue by VinceCar** [lorenzo-rovigatti/tacoxDNA#17]
Hi everyone, 
I've tested this script on some of my designs (produced using Maya 2018 on IMac) and the resulting topology files were not correct. In particular the C and G bases results swap. The problem repeated with simpler structures of ds and ss strands (in the attached zip folder, there are 2 Maya files, the first containing a ds AGAGA sequence that becomes ACACA while the second contains a mixed sequence of ds-ss CCCCC becoming GGGGG).
[tests.zip](https://github.com/lorenzo-rovigatti/tacoxDNA/files/4434120/tests.zip)

**Comment by lorenzo-rovigatti** [comment]
Hey there, thanks a lot for pointing this out. We'll work on a fix asap.

**Comment by lorenzo-rovigatti** [comment]
The issue has been fixed in commit c0f2ac5.
