### ISSUE TITLE
A problem when convert oxDNA file into pdb file

### ISSUE THREAD

**Issue by HollandDove** [lorenzo-rovigatti/tacoxDNA#33]
Hi! I recently find a problem when I use tacoxDNA to convert oxDNA file into pdb file. I find that in the pymol, when I open the generated pdb file, the cartoon view shows a lot of fragments, instead of a straight chain.  Is there any information that is ignored in the convertion process?
I attach oxDNA file and pdb file genratated below.
I will be very pleasure if anyone know how to solve this.

![pdb](https://user-images.githubusercontent.com/54866510/116937176-b4a9fb80-ac1d-11eb-9ddc-a6cd9ee7e48b.png)
![oxdna](https://user-images.githubusercontent.com/54866510/116937179-b5429200-ac1d-11eb-9cdc-d253ff333512.png)

**Comment by lorenzo-rovigatti** [comment]
Hi there,

the conversion often leaves atoms quite far from each other so that common visualisation software such as pymol or vmd don't see them connected. You first need to relax the structure by using an all-atom force field.

cheers,
Lorenzo
