### ISSUE TITLE
Problem in sequence adding for CaDNAno --> OxDNA conversion

### ISSUE THREAD

**Issue by Prateek1410** [lorenzo-rovigatti/tacoxDNA#36]
Hello!

When I add the CaDNAno generated sequence as an input I get an error, _CRITICAL: KeyError while converting base names to integer; check the sequence file_. I write the command as follows:  _cadnano_oxDNA.py design.json sq -q design.csv_ . 

I gather I have to change the formatting of my sequence file. Could you please suggest some way to do this? Thanks a lot for the tools and thank you for your time and consideration. 

Warm Regards
Prateek

**Comment by lorenzo-rovigatti** [comment]
This is a known issue. You can check #12 for a work around.
