### ISSUE TITLE
Length of an OxDNA unit

### ISSUE THREAD

**Issue by thenlevy** [lorenzo-rovigatti/tacoxDNA#37]
Hello,
I am working on a pdb export for ENSnano and I have been taking inspiration from the method used in tacoxDNA. 
While reading the code I came upon the constant `FROM_OXDNA_TO_ANGSTROM = 8.518` defined in `src/libs/pdb.py`
I am a bit surprised by this value because I assumed that the coordinate in OxDNA were expressed in nanometers. 

Is an oxDNA "unit" 8.518 angstrom long or is a specificity of the algorithm for converting to the pdb format ?

**Comment by lorenzo-rovigatti** [comment]
A oxDNA unit of length does indeed correspond to 0.8518 nanometers (or 8.518 angstroms). A table with conversion factors between oxDNA and SI units can be found [here](https://dna.physics.ox.ac.uk/index.php/DNA_model_introduction).
