### ISSUE TITLE
Unphysical stretched bond after coarse-graining 

### ISSUE THREAD

**Issue by swapnilbaral-git** [lorenzo-rovigatti/tacoxDNA#38]
I have DNA origami pdb file that I converted/coarse-grained to oxDNA file using tacoxDNA scipt (PDB_oxdna.py). The oxDNA structure has stretched unphysical bonds after coarse-graining. 

![image](https://user-images.githubusercontent.com/65355406/172074383-dfe508cd-786e-4fd8-ae1f-abaebd73bc85.png)

**Comment by lorenzo-rovigatti** [comment]
It's a bit hard to understand what's going on I can't see the original pdb file.

**Comment by swapnilbaral-git** [comment]
I cannot find a way to attach pdb file here. Is there a way that I do not know.

**Comment by swapnilbaral-git** [comment]
[NR_01-4.fixed.zip](https://github.com/lorenzo-rovigatti/tacoxDNA/files/8871752/NR_01-4.fixed.zip)
Attached.

**Comment by lorenzo-rovigatti** [comment]
The pdb you attached list all nucleotides as they were part of the same strand: there is not distinction between scaffold and staples and therefore tacoxDNA (correctly) consider all consecutive nucleotides as connected by a backbone bond, which results in the stretched bonds you see when you look at the oxDNA configuration.

You need to separate different strands with a TER statement (see [PDB specifications](https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#TER) for more info.
