### ISSUE TITLE
support scadnano import

### ISSUE THREAD

**Issue by dave-doty** [lorenzo-rovigatti/tacoxDNA#39]
This is a request to support importing from scadnano.

Since the scadnano python package supports export to the oxDNA format, this is as simple as installing scadnano via `pip install scadnano`, then execute the following:

```python
import scadnano as sc

design = sc.Design.from_scadnano_file('my_design.sc')
dat, top = design.to_oxdna_format()
```

Then `dat` and `top` are strings with the contents of the .dat and .top files of oxDNA. You can also create the files directly by calling `design.write_oxdna_files()` instead of `design.to_oxdna_format()`.

See

https://scadnano-python-package.readthedocs.io/en/latest/#scadnano.Design.from_scadnano_file
https://scadnano-python-package.readthedocs.io/en/latest/#scadnano.Design.to_oxdna_format
https://scadnano-python-package.readthedocs.io/en/latest/#scadnano.Design.write_oxdna_files

**Comment by lorenzo-rovigatti** [comment]
Hey, thanks for the suggestion. Just to be sure, you're asking that a script containing those lines (+ some option handling I suppose) be added to tacoxDNA, right?

**Comment by dave-doty** [comment]
> Hey, thanks for the suggestion. Just to be sure, you're asking that a script containing those lines (+ some option handling I suppose) be added to tacoxDNA, right?

I'm not sure. I don't know how tacoxDNA interfaces with other tools, e.g., if it's used by oxView to import files. I also thought that possibly there's a tacoxDNA server somewhere so that people can use the tools without going to the command line.

So I was essentially asking for it to be integrated, how the other tools are integrated, but pointing out that the logic of converting the formats is already implemented in the scadnano package, so it's hopefully very easy to implement.

**Comment by lorenzo-rovigatti** [comment]
I have just added a branch where I created a scadnano -> oxDNA converter. I never used scadnano myself, so I don't know whether it takes optional arguments or if you want to add some more features to the converter. If you have some spare time can you have a look at it? Just checkout the `scadnano` branch. The new script is `src/scadnano_oxDNA.py`

**Comment by dave-doty** [comment]
> I have just added a branch where I created a scadnano -> oxDNA converter. I never used scadnano myself, so I don't know whether it takes optional arguments or if you want to add some more features to the converter. If you have some spare time can you have a look at it? Just checkout the `scadnano` branch. The new script is `src/scadnano_oxDNA.py`

Looks good! I don't think it needs any optional parameters.

**Comment by lorenzo-rovigatti** [comment]
Thanks for the feedback! I have merged the branch back into master.

**Comment by dave-doty** [comment]
> Thanks for the feedback! I have merged the branch back into master.

Great? Do you maintain the website too? http://tacoxdna.sissa.it/ Would it be too much trouble to copy/paste one of the existing pages that converts to oxDNA and substitute a call to the scadnano script?

**Comment by lorenzo-rovigatti** [comment]
I used to maintain it, but I have since stopped updating it. I'll try to get access back and update it as soon as I can

**Comment by lorenzo-rovigatti** [comment]
OK, I have managed to get my credentials back and I have added a scadnano->oxDNA conversion page.
